{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: beacon
  labels:
    {{- include "beacon.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.ingress.tls }}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.clusterIssuer }}
    {{- end }}
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    {{- range prepend (.Values.extraHosts | default list) .Values.host }}
    - host: {{ . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "beacon.name" "nginx" }}
                port:
                  number: 80
    {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        {{- range prepend (.Values.extraHosts | default list) .Values.host }}
        - {{ . }}
        {{- end }}
      secretName: beacon-tls
  {{- end }}
{{- end }}
