apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "beacon.name" "redis" }}
  labels:
    {{- include "beacon.labels" . | nindent 4 }}
    {{- include "beacon.selector" "redis" | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "beacon.selector" "redis" | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "beacon.labels" . | nindent 8 }}
        {{- include "beacon.selector" "redis" | nindent 8 }}
    spec:
      securityContext:
        fsGroup: 999
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: redis
          image: {{ .Values.images.redis }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["redis-server", "--appendonly", "yes"]
          ports:
            - containerPort: 6379
          readinessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            {{- toYaml .Values.resources.redis | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: beacon-redis-data
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "beacon.name" "redis" }}
  labels:
    {{- include "beacon.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "beacon.selector" "redis" | nindent 4 }}
  ports:
    - port: 6379
      targetPort: 6379
